// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqgb0i9JTRK6hwtPynILLWy-dJ3rpFnwo',
    appId: '1:546277714389:web:0c4141cc17b7fdda54755c',
    messagingSenderId: '546277714389',
    projectId: 'vaplearner',
    authDomain: 'vaplearner.firebaseapp.com',
    storageBucket: 'vaplearner.firebasestorage.app',
    measurementId: 'G-MBK0ZZRYGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMtAxHSDT1V5xWtCzK885pExPhB6XUfxI',
    appId: '1:546277714389:android:a61264636bbda4e954755c',
    messagingSenderId: '546277714389',
    projectId: 'vaplearner',
    storageBucket: 'vaplearner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzvel_KLsWtJ7IaFGmp6mWPqrpL1a3LKM',
    appId: '1:546277714389:ios:78e275b52d48b39d54755c',
    messagingSenderId: '546277714389',
    projectId: 'vaplearner',
    storageBucket: 'vaplearner.firebasestorage.app',
    androidClientId: '546277714389-rvup0t0oc0phq37tro7bqj833fjr7sfp.apps.googleusercontent.com',
    iosClientId: '546277714389-melt3h7m56g2esm3snfrk0inrt0l4dgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzvel_KLsWtJ7IaFGmp6mWPqrpL1a3LKM',
    appId: '1:546277714389:ios:78e275b52d48b39d54755c',
    messagingSenderId: '546277714389',
    projectId: 'vaplearner',
    storageBucket: 'vaplearner.firebasestorage.app',
    androidClientId: '546277714389-rvup0t0oc0phq37tro7bqj833fjr7sfp.apps.googleusercontent.com',
    iosClientId: '546277714389-melt3h7m56g2esm3snfrk0inrt0l4dgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqgb0i9JTRK6hwtPynILLWy-dJ3rpFnwo',
    appId: '1:546277714389:web:61eb89ca6cb7653454755c',
    messagingSenderId: '546277714389',
    projectId: 'vaplearner',
    authDomain: 'vaplearner.firebaseapp.com',
    storageBucket: 'vaplearner.firebasestorage.app',
    measurementId: 'G-JZWYSR5ESB',
  );

}